const gender = ['공용', '남성', '여성']
const color = ['white','black','blue','gray','pink','red','yellow']



const menClothList = [{
        id: 'men01',
        src: './img/men01.jpg',
        gender: gender[1],
        name: '핫써머 씨어서커 우븐반바지',
        price: 69000,
        href: '#!',
        sold: 12,
        color: color[0],
        size: [75,80,85]
    },
    {
        id: 'men02',
        src: './img/men02.jpg',
        gender: gender[0],
        name: '핫써머 씨어서커 아노락 바람막이',
        price: 119000,
        href: '#!',
        sold: 6,
        color: color[2],
        size: [80,90,100]
    },
    {
        id: 'men03',
        src: './img/men03.jpg',
        gender: gender[1],
        name: '컴포트핏 인터내셔널 반팔 카라티',
        price: 69000,
        href: '#!',
        sold: 2,
        color: color[0],
        size: [75,85,95]
    },
    {
        id: 'men04',
        src: './img/men04.jpg',
        gender: gender[0],
        name: '핫써머 씨어서커 아노락 바람막이',
        price: 119000,
        href: '#!',
        sold: 24,
        color: color[0],
        size: [100,105,110]
    },
    {
        id: 'men05',
        src: './img/men05.jpg',
        gender: gender[1],
        name: '핫써머 사이드프린트 우븐 반바지',
        price: 69000,
        href: '#!',
        sold: 19,
        color: color[1],
        size: [105,110,115],
    },
    {
        id: 'men06',
        src: './img/men06.jpg',
        gender: gender[0],
        name: '핫써머 모노그램 우븐 반바지',
        price: 79000,
        href: '#!',
        sold: 3,
        color: color[2],
        size: [90,95,100],
    },
    {
        id: 'men07',
        src: './img/men07.jpg',
        gender: gender[0],
        name: '컴포트핏 인터내셔널 6부 반바지',
        price: 59000,
        href: '#!',
        sold: 16,
        color: color[0],
        size: [80,85,90]
    },
    {
        id: 'men08',
        src: './img/men08.jpg',
        gender: gender[1],
        name: '페스타 그래픽 티셔츠',
        price: 49000,
        href: '#!',
        sold: 21,
        color: color[0],
        size: [95,100,105],
    },
    {
        id: 'men09',
        src: './img/men09.jpg',
        gender: gender[0],
        name: '레터링 그래픽 티셔츠',
        price: 49000,
        href: '#!',
        sold: 15,
        color: color[2],
        size: [80,85,90,95,100],
    },
    {
        id: 'men10',
        src: './img/men10.jpg',
        gender: gender[1],
        name: '레코드 그래픽 티셔츠',
        price: 59000,
        href: '#!',
        sold: 4,
        color: color[4],
        size: [95,100,105],
    },
    {
        id: 'men11',
        src: './img/men11.jpg',
        gender: gender[1],
        name: 'havefun 그래픽 티셔츠',
        price: 49000,
        href: '#!',
        sold: 5,
        color: color[0],
        size: [100,105,110],
    },
    {
        id: 'men12',
        src: './img/men12.jpg',
        gender: gender[0],
        name: '컴포트핏 인터내셔널 우븐 후드티',
        price: 119000,
        href: '#!',
        sold: 13,
        color: color[3],
        size: [75,80,85,100],
    },
    {
        id: 'men13',
        src: './img/men13.jpg',
        gender: gender[1],
        name: '컴포트핏 인터내셔널 우븐 후드티',
        price: 119000,
        href: '#!',
        sold: 23,
        color: color[5],
        size: [90,95,100,105],
    },
    {
        id: 'men14',
        src: './img/men14.jpg',
        gender: gender[0],
        name: '컴포트핏 인터내셔널 우븐 후드티',
        price: 119000,
        href: '#!',
        sold: 22,
        color: color[6],
        size: [85,90,95,100],
    },
    {
        id: 'men15',
        src: './img/men15.jpg',
        gender: gender[1],
        name: '컴포트핏 인터내셔널 우븐 후드티',
        price: 119000,
        href: '#!',
        sold: 1,
        color: color[1],
        size: [90,95,100,105],
    },
    {
        id: 'men16',
        src: './img/men16.jpg',
        gender: gender[0],
        name: '컴포트핏 인터내셔널 스몰로고 카라티',
        price: 79000,
        href: '#!',
        sold: 18,
        color: color[1],
        size: [75,80,85,90],
    },
    {
        id: 'men17',
        src: './img/men17.jpg',
        gender: gender[0],
        name: '컴포트핏 플래그 반팔티',
        price: 39000,
        href: '#!',
        sold: 14,
        color: color[4],
        size: [95,100,105,110],
    },
    {
        id: 'men18',
        src: './img/men18.jpg',
        gender: gender[1],
        name: '컴포트핏 플래그 반팔티',
        price: 39000,
        href: '#!',
        sold: 8,
        color: color[0],
        size: [75,95],
    },
    {
        id: 'men19',
        src: './img/men19.jpg',
        gender: gender[0],
        name: '컴포트핏 플래그 반팔티',
        price: 39000,
        href: '#!',
        sold: 7,
        color: color[1],
        size: [75,85,95,105],
    },
    {
        id: 'men20',
        src: './img/men20.jpg',
        gender: gender[1],
        name: '컴포트핏 마인드블로어 반팔티',
        price: 39000,
        href: '#!',
        sold: 20,
        color: color[1],
        size: [80,90,100,110],
    },
    {
        id: 'men21',
        src: './img/men21.jpg',
        gender: gender[1],
        name: '핫써머 모노그램 나시티',
        price: 49000,
        href: '#!',
        sold: 10,
        color: color[2],
        size: [75,80,85,90,95],
    },
    {
        id: 'men22',
        src: './img/men22.jpg',
        gender: gender[1],
        name: '핫써머 우븐 포켓 반바지',
        price: 69000,
        href: '#!',
        sold: 11,
        color: color[2],
        size: [80,85,90,100],
    },
    {
        id: 'men23',
        src: './img/men23.jpg',
        gender: gender[0],
        name: '핫써머 씨어서커 우븐반바지',
        price: 69000,
        href: '#!',
        sold: 17,
        color: color[2],
        size: [90,100,110],
    },
    {
        id: 'men24',
        src: './img/men24.jpg',
        gender: gender[0],
        name: '핫써머 씨어서커 아노락 바람막이',
        price: 119000,
        href: '#!',
        sold: 9,
        color: color[0],
        size: [85,90,95],
    },



]

export default menClothList